apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-teste
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: pod
    repoURL: https://github.com/brunofurtado/openshift-gitops-getting-started
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
